//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./SocialBlacklistService_types');
//HELPER FUNCTIONS AND STRUCTURES

ISocialServiceAddSocialBlacklist_addSocialBlacklist_args = function(args) {
  this.blackUserId = null;
  if (args) {
    if (args.blackUserId !== undefined) {
      this.blackUserId = args.blackUserId;
    }
  }
};
ISocialServiceAddSocialBlacklist_addSocialBlacklist_args.prototype = {};
ISocialServiceAddSocialBlacklist_addSocialBlacklist_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I64) {
        this.blackUserId = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ISocialServiceAddSocialBlacklist_addSocialBlacklist_args.prototype.write = function(output) {
  output.writeStructBegin('ISocialServiceAddSocialBlacklist_addSocialBlacklist_args');
  if (this.blackUserId !== null && this.blackUserId !== undefined) {
    output.writeFieldBegin('blackUserId', Thrift.Type.I64, 1);
    output.writeI64(this.blackUserId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ISocialServiceAddSocialBlacklist_addSocialBlacklist_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ISocialServiceAddSocialBlacklist_addSocialBlacklist_result.prototype = {};
ISocialServiceAddSocialBlacklist_addSocialBlacklist_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ISocialServiceAddSocialBlacklist_addSocialBlacklist_result.prototype.write = function(output) {
  output.writeStructBegin('ISocialServiceAddSocialBlacklist_addSocialBlacklist_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ISocialServiceAddSocialBlacklistClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
ISocialServiceAddSocialBlacklistClient.prototype = {};
ISocialServiceAddSocialBlacklistClient.prototype.seqid = function() { return this._seqid; }
ISocialServiceAddSocialBlacklistClient.prototype.new_seqid = function() { return this._seqid += 1; }
ISocialServiceAddSocialBlacklistClient.prototype.addSocialBlacklist = function(blackUserId, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_addSocialBlacklist(blackUserId);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_addSocialBlacklist(blackUserId);
  }
};

ISocialServiceAddSocialBlacklistClient.prototype.send_addSocialBlacklist = function(blackUserId) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('addSocialBlacklist', Thrift.MessageType.CALL, this.seqid());
  var args = new ISocialServiceAddSocialBlacklist_addSocialBlacklist_args();
  args.blackUserId = blackUserId;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ISocialServiceAddSocialBlacklistClient.prototype.recv_addSocialBlacklist = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ISocialServiceAddSocialBlacklist_addSocialBlacklist_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('addSocialBlacklist failed: unknown result');
};
ISocialServiceAddSocialBlacklistProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
ISocialServiceAddSocialBlacklistProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

ISocialServiceAddSocialBlacklistProcessor.prototype.process_addSocialBlacklist = function(seqid, input, output) {
  var args = new ISocialServiceAddSocialBlacklist_addSocialBlacklist_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.addSocialBlacklist.length === 1) {
    Q.fcall(this._handler.addSocialBlacklist, args.blackUserId)
      .then(function(result) {
        var result = new ISocialServiceAddSocialBlacklist_addSocialBlacklist_result({success: result});
        output.writeMessageBegin("addSocialBlacklist", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new ISocialServiceAddSocialBlacklist_addSocialBlacklist_result(err);
        output.writeMessageBegin("addSocialBlacklist", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.addSocialBlacklist(args.blackUserId,  function (err, result) {
      var result = new ISocialServiceAddSocialBlacklist_addSocialBlacklist_result((err != null ? err : {success: result}));
      output.writeMessageBegin("addSocialBlacklist", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

