//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var TAdminLabel_ttypes = require('./TAdminLabel_types')
var TAdminLabelQueryData_ttypes = require('./TAdminLabelQueryData_types')
var TAdminPost_ttypes = require('./TAdminPost_types')
var TAdminActivityApply_ttypes = require('./TAdminActivityApply_types')
var TAdminComment_ttypes = require('./TAdminComment_types')
var TAdminCommentQueryData_ttypes = require('./TAdminCommentQueryData_types')
var TAdminReason_ttypes = require('./TAdminReason_types')
var TAdminCityPost_ttypes = require('./TAdminCityPost_types')
var TAdminPostQueryData_ttypes = require('./TAdminPostQueryData_types')
var TAdminPostInform_ttypes = require('./TAdminPostInform_types')


var ttypes = require('./SocialAdminService_types');
//HELPER FUNCTIONS AND STRUCTURES

ISocialAdminServiceGetAdminLabelList_getAdminLabelList_args = function(args) {
  this.params = null;
  if (args) {
    if (args.params !== undefined) {
      this.params = args.params;
    }
  }
};
ISocialAdminServiceGetAdminLabelList_getAdminLabelList_args.prototype = {};
ISocialAdminServiceGetAdminLabelList_getAdminLabelList_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.params = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ISocialAdminServiceGetAdminLabelList_getAdminLabelList_args.prototype.write = function(output) {
  output.writeStructBegin('ISocialAdminServiceGetAdminLabelList_getAdminLabelList_args');
  if (this.params !== null && this.params !== undefined) {
    output.writeFieldBegin('params', Thrift.Type.STRING, 1);
    output.writeString(this.params);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ISocialAdminServiceGetAdminLabelList_getAdminLabelList_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ISocialAdminServiceGetAdminLabelList_getAdminLabelList_result.prototype = {};
ISocialAdminServiceGetAdminLabelList_getAdminLabelList_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new TAdminLabelQueryData_ttypes.TAdminLabelQueryData();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ISocialAdminServiceGetAdminLabelList_getAdminLabelList_result.prototype.write = function(output) {
  output.writeStructBegin('ISocialAdminServiceGetAdminLabelList_getAdminLabelList_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ISocialAdminServiceGetAdminLabelListClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
ISocialAdminServiceGetAdminLabelListClient.prototype = {};
ISocialAdminServiceGetAdminLabelListClient.prototype.seqid = function() { return this._seqid; }
ISocialAdminServiceGetAdminLabelListClient.prototype.new_seqid = function() { return this._seqid += 1; }
ISocialAdminServiceGetAdminLabelListClient.prototype.getAdminLabelList = function(params, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getAdminLabelList(params);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getAdminLabelList(params);
  }
};

ISocialAdminServiceGetAdminLabelListClient.prototype.send_getAdminLabelList = function(params) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getAdminLabelList', Thrift.MessageType.CALL, this.seqid());
  var args = new ISocialAdminServiceGetAdminLabelList_getAdminLabelList_args();
  args.params = params;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ISocialAdminServiceGetAdminLabelListClient.prototype.recv_getAdminLabelList = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ISocialAdminServiceGetAdminLabelList_getAdminLabelList_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getAdminLabelList failed: unknown result');
};
ISocialAdminServiceGetAdminLabelListProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
ISocialAdminServiceGetAdminLabelListProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

ISocialAdminServiceGetAdminLabelListProcessor.prototype.process_getAdminLabelList = function(seqid, input, output) {
  var args = new ISocialAdminServiceGetAdminLabelList_getAdminLabelList_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getAdminLabelList.length === 1) {
    Q.fcall(this._handler.getAdminLabelList, args.params)
      .then(function(result) {
        var result = new ISocialAdminServiceGetAdminLabelList_getAdminLabelList_result({success: result});
        output.writeMessageBegin("getAdminLabelList", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new ISocialAdminServiceGetAdminLabelList_getAdminLabelList_result(err);
        output.writeMessageBegin("getAdminLabelList", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getAdminLabelList(args.params,  function (err, result) {
      var result = new ISocialAdminServiceGetAdminLabelList_getAdminLabelList_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getAdminLabelList", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

