//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var TAdminLabel_ttypes = require('./TAdminLabel_types')
var TAdminLabelQueryData_ttypes = require('./TAdminLabelQueryData_types')
var TAdminPost_ttypes = require('./TAdminPost_types')
var TAdminActivityApply_ttypes = require('./TAdminActivityApply_types')
var TAdminComment_ttypes = require('./TAdminComment_types')
var TAdminCommentQueryData_ttypes = require('./TAdminCommentQueryData_types')
var TAdminReason_ttypes = require('./TAdminReason_types')
var TAdminCityPost_ttypes = require('./TAdminCityPost_types')
var TAdminPostQueryData_ttypes = require('./TAdminPostQueryData_types')
var TAdminPostInform_ttypes = require('./TAdminPostInform_types')


var ttypes = require('./SocialAdminService_types');
//HELPER FUNCTIONS AND STRUCTURES

ISocialAdminServiceGetAdminCommentList_getAdminCommentList_args = function(args) {
  this.postId = null;
  this.content = null;
  this.currentPage = null;
  this.pageSize = null;
  if (args) {
    if (args.postId !== undefined) {
      this.postId = args.postId;
    }
    if (args.content !== undefined) {
      this.content = args.content;
    }
    if (args.currentPage !== undefined) {
      this.currentPage = args.currentPage;
    }
    if (args.pageSize !== undefined) {
      this.pageSize = args.pageSize;
    }
  }
};
ISocialAdminServiceGetAdminCommentList_getAdminCommentList_args.prototype = {};
ISocialAdminServiceGetAdminCommentList_getAdminCommentList_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.postId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.content = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.currentPage = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.pageSize = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ISocialAdminServiceGetAdminCommentList_getAdminCommentList_args.prototype.write = function(output) {
  output.writeStructBegin('ISocialAdminServiceGetAdminCommentList_getAdminCommentList_args');
  if (this.postId !== null && this.postId !== undefined) {
    output.writeFieldBegin('postId', Thrift.Type.I32, 1);
    output.writeI32(this.postId);
    output.writeFieldEnd();
  }
  if (this.content !== null && this.content !== undefined) {
    output.writeFieldBegin('content', Thrift.Type.STRING, 2);
    output.writeString(this.content);
    output.writeFieldEnd();
  }
  if (this.currentPage !== null && this.currentPage !== undefined) {
    output.writeFieldBegin('currentPage', Thrift.Type.I32, 3);
    output.writeI32(this.currentPage);
    output.writeFieldEnd();
  }
  if (this.pageSize !== null && this.pageSize !== undefined) {
    output.writeFieldBegin('pageSize', Thrift.Type.I32, 4);
    output.writeI32(this.pageSize);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ISocialAdminServiceGetAdminCommentList_getAdminCommentList_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ISocialAdminServiceGetAdminCommentList_getAdminCommentList_result.prototype = {};
ISocialAdminServiceGetAdminCommentList_getAdminCommentList_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new TAdminCommentQueryData_ttypes.TAdminCommentQueryData();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ISocialAdminServiceGetAdminCommentList_getAdminCommentList_result.prototype.write = function(output) {
  output.writeStructBegin('ISocialAdminServiceGetAdminCommentList_getAdminCommentList_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ISocialAdminServiceGetAdminCommentListClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
ISocialAdminServiceGetAdminCommentListClient.prototype = {};
ISocialAdminServiceGetAdminCommentListClient.prototype.seqid = function() { return this._seqid; }
ISocialAdminServiceGetAdminCommentListClient.prototype.new_seqid = function() { return this._seqid += 1; }
ISocialAdminServiceGetAdminCommentListClient.prototype.getAdminCommentList = function(postId, content, currentPage, pageSize, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getAdminCommentList(postId, content, currentPage, pageSize);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getAdminCommentList(postId, content, currentPage, pageSize);
  }
};

ISocialAdminServiceGetAdminCommentListClient.prototype.send_getAdminCommentList = function(postId, content, currentPage, pageSize) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getAdminCommentList', Thrift.MessageType.CALL, this.seqid());
  var args = new ISocialAdminServiceGetAdminCommentList_getAdminCommentList_args();
  args.postId = postId;
  args.content = content;
  args.currentPage = currentPage;
  args.pageSize = pageSize;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ISocialAdminServiceGetAdminCommentListClient.prototype.recv_getAdminCommentList = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ISocialAdminServiceGetAdminCommentList_getAdminCommentList_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getAdminCommentList failed: unknown result');
};
ISocialAdminServiceGetAdminCommentListProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
ISocialAdminServiceGetAdminCommentListProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

ISocialAdminServiceGetAdminCommentListProcessor.prototype.process_getAdminCommentList = function(seqid, input, output) {
  var args = new ISocialAdminServiceGetAdminCommentList_getAdminCommentList_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getAdminCommentList.length === 4) {
    Q.fcall(this._handler.getAdminCommentList, args.postId, args.content, args.currentPage, args.pageSize)
      .then(function(result) {
        var result = new ISocialAdminServiceGetAdminCommentList_getAdminCommentList_result({success: result});
        output.writeMessageBegin("getAdminCommentList", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new ISocialAdminServiceGetAdminCommentList_getAdminCommentList_result(err);
        output.writeMessageBegin("getAdminCommentList", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getAdminCommentList(args.postId, args.content, args.currentPage, args.pageSize,  function (err, result) {
      var result = new ISocialAdminServiceGetAdminCommentList_getAdminCommentList_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getAdminCommentList", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

