//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var TAdminLabel_ttypes = require('./TAdminLabel_types')
var TAdminLabelQueryData_ttypes = require('./TAdminLabelQueryData_types')
var TAdminPost_ttypes = require('./TAdminPost_types')
var TAdminActivityApply_ttypes = require('./TAdminActivityApply_types')
var TAdminComment_ttypes = require('./TAdminComment_types')
var TAdminCommentQueryData_ttypes = require('./TAdminCommentQueryData_types')
var TAdminReason_ttypes = require('./TAdminReason_types')
var TAdminCityPost_ttypes = require('./TAdminCityPost_types')
var TAdminPostQueryData_ttypes = require('./TAdminPostQueryData_types')
var TAdminPostInform_ttypes = require('./TAdminPostInform_types')


var ttypes = require('./SocialAdminService_types');
//HELPER FUNCTIONS AND STRUCTURES

ISocialAdminServiceUpdateAdminLabelStatus_updateAdminLabelStatus_args = function(args) {
  this.label = null;
  if (args) {
    if (args.label !== undefined) {
      this.label = args.label;
    }
  }
};
ISocialAdminServiceUpdateAdminLabelStatus_updateAdminLabelStatus_args.prototype = {};
ISocialAdminServiceUpdateAdminLabelStatus_updateAdminLabelStatus_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.label = new TAdminLabel_ttypes.TAdminLabel();
        this.label.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ISocialAdminServiceUpdateAdminLabelStatus_updateAdminLabelStatus_args.prototype.write = function(output) {
  output.writeStructBegin('ISocialAdminServiceUpdateAdminLabelStatus_updateAdminLabelStatus_args');
  if (this.label !== null && this.label !== undefined) {
    output.writeFieldBegin('label', Thrift.Type.STRUCT, 1);
    this.label.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ISocialAdminServiceUpdateAdminLabelStatus_updateAdminLabelStatus_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ISocialAdminServiceUpdateAdminLabelStatus_updateAdminLabelStatus_result.prototype = {};
ISocialAdminServiceUpdateAdminLabelStatus_updateAdminLabelStatus_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ISocialAdminServiceUpdateAdminLabelStatus_updateAdminLabelStatus_result.prototype.write = function(output) {
  output.writeStructBegin('ISocialAdminServiceUpdateAdminLabelStatus_updateAdminLabelStatus_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ISocialAdminServiceUpdateAdminLabelStatusClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
ISocialAdminServiceUpdateAdminLabelStatusClient.prototype = {};
ISocialAdminServiceUpdateAdminLabelStatusClient.prototype.seqid = function() { return this._seqid; }
ISocialAdminServiceUpdateAdminLabelStatusClient.prototype.new_seqid = function() { return this._seqid += 1; }
ISocialAdminServiceUpdateAdminLabelStatusClient.prototype.updateAdminLabelStatus = function(label, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_updateAdminLabelStatus(label);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_updateAdminLabelStatus(label);
  }
};

ISocialAdminServiceUpdateAdminLabelStatusClient.prototype.send_updateAdminLabelStatus = function(label) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('updateAdminLabelStatus', Thrift.MessageType.CALL, this.seqid());
  var args = new ISocialAdminServiceUpdateAdminLabelStatus_updateAdminLabelStatus_args();
  args.label = label;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ISocialAdminServiceUpdateAdminLabelStatusClient.prototype.recv_updateAdminLabelStatus = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ISocialAdminServiceUpdateAdminLabelStatus_updateAdminLabelStatus_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('updateAdminLabelStatus failed: unknown result');
};
ISocialAdminServiceUpdateAdminLabelStatusProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
ISocialAdminServiceUpdateAdminLabelStatusProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

ISocialAdminServiceUpdateAdminLabelStatusProcessor.prototype.process_updateAdminLabelStatus = function(seqid, input, output) {
  var args = new ISocialAdminServiceUpdateAdminLabelStatus_updateAdminLabelStatus_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.updateAdminLabelStatus.length === 1) {
    Q.fcall(this._handler.updateAdminLabelStatus, args.label)
      .then(function(result) {
        var result = new ISocialAdminServiceUpdateAdminLabelStatus_updateAdminLabelStatus_result({success: result});
        output.writeMessageBegin("updateAdminLabelStatus", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new ISocialAdminServiceUpdateAdminLabelStatus_updateAdminLabelStatus_result(err);
        output.writeMessageBegin("updateAdminLabelStatus", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.updateAdminLabelStatus(args.label,  function (err, result) {
      var result = new ISocialAdminServiceUpdateAdminLabelStatus_updateAdminLabelStatus_result((err != null ? err : {success: result}));
      output.writeMessageBegin("updateAdminLabelStatus", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

