//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var TAdminLabel_ttypes = require('./TAdminLabel_types')
var TAdminLabelQueryData_ttypes = require('./TAdminLabelQueryData_types')
var TAdminPost_ttypes = require('./TAdminPost_types')
var TAdminActivityApply_ttypes = require('./TAdminActivityApply_types')
var TAdminComment_ttypes = require('./TAdminComment_types')
var TAdminCommentQueryData_ttypes = require('./TAdminCommentQueryData_types')
var TAdminReason_ttypes = require('./TAdminReason_types')
var TAdminCityPost_ttypes = require('./TAdminCityPost_types')
var TAdminPostQueryData_ttypes = require('./TAdminPostQueryData_types')
var TAdminPostInform_ttypes = require('./TAdminPostInform_types')


var ttypes = require('./SocialAdminService_types');
//HELPER FUNCTIONS AND STRUCTURES

ISocialAdminServiceDeleteAdminPost_deleteAdminPost_args = function(args) {
  this.post = null;
  if (args) {
    if (args.post !== undefined) {
      this.post = args.post;
    }
  }
};
ISocialAdminServiceDeleteAdminPost_deleteAdminPost_args.prototype = {};
ISocialAdminServiceDeleteAdminPost_deleteAdminPost_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.post = new TAdminPost_ttypes.TAdminPost();
        this.post.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ISocialAdminServiceDeleteAdminPost_deleteAdminPost_args.prototype.write = function(output) {
  output.writeStructBegin('ISocialAdminServiceDeleteAdminPost_deleteAdminPost_args');
  if (this.post !== null && this.post !== undefined) {
    output.writeFieldBegin('post', Thrift.Type.STRUCT, 1);
    this.post.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ISocialAdminServiceDeleteAdminPost_deleteAdminPost_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ISocialAdminServiceDeleteAdminPost_deleteAdminPost_result.prototype = {};
ISocialAdminServiceDeleteAdminPost_deleteAdminPost_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ISocialAdminServiceDeleteAdminPost_deleteAdminPost_result.prototype.write = function(output) {
  output.writeStructBegin('ISocialAdminServiceDeleteAdminPost_deleteAdminPost_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ISocialAdminServiceDeleteAdminPostClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
ISocialAdminServiceDeleteAdminPostClient.prototype = {};
ISocialAdminServiceDeleteAdminPostClient.prototype.seqid = function() { return this._seqid; }
ISocialAdminServiceDeleteAdminPostClient.prototype.new_seqid = function() { return this._seqid += 1; }
ISocialAdminServiceDeleteAdminPostClient.prototype.deleteAdminPost = function(post, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_deleteAdminPost(post);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_deleteAdminPost(post);
  }
};

ISocialAdminServiceDeleteAdminPostClient.prototype.send_deleteAdminPost = function(post) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('deleteAdminPost', Thrift.MessageType.CALL, this.seqid());
  var args = new ISocialAdminServiceDeleteAdminPost_deleteAdminPost_args();
  args.post = post;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ISocialAdminServiceDeleteAdminPostClient.prototype.recv_deleteAdminPost = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ISocialAdminServiceDeleteAdminPost_deleteAdminPost_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('deleteAdminPost failed: unknown result');
};
ISocialAdminServiceDeleteAdminPostProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
ISocialAdminServiceDeleteAdminPostProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

ISocialAdminServiceDeleteAdminPostProcessor.prototype.process_deleteAdminPost = function(seqid, input, output) {
  var args = new ISocialAdminServiceDeleteAdminPost_deleteAdminPost_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.deleteAdminPost.length === 1) {
    Q.fcall(this._handler.deleteAdminPost, args.post)
      .then(function(result) {
        var result = new ISocialAdminServiceDeleteAdminPost_deleteAdminPost_result({success: result});
        output.writeMessageBegin("deleteAdminPost", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new ISocialAdminServiceDeleteAdminPost_deleteAdminPost_result(err);
        output.writeMessageBegin("deleteAdminPost", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.deleteAdminPost(args.post,  function (err, result) {
      var result = new ISocialAdminServiceDeleteAdminPost_deleteAdminPost_result((err != null ? err : {success: result}));
      output.writeMessageBegin("deleteAdminPost", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

