//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

IActivityAdminServiceGetAdminPostListByActivityId_getAdminPostListByActivityId_args = function(args) {
  this.id = null;
  this.currentPage = null;
  this.pageSize = null;
  if (args) {
    if (args.id !== undefined) {
      this.id = args.id;
    }
    if (args.currentPage !== undefined) {
      this.currentPage = args.currentPage;
    }
    if (args.pageSize !== undefined) {
      this.pageSize = args.pageSize;
    }
  }
};
IActivityAdminServiceGetAdminPostListByActivityId_getAdminPostListByActivityId_args.prototype = {};
IActivityAdminServiceGetAdminPostListByActivityId_getAdminPostListByActivityId_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.id = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.currentPage = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.pageSize = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

IActivityAdminServiceGetAdminPostListByActivityId_getAdminPostListByActivityId_args.prototype.write = function(output) {
  output.writeStructBegin('IActivityAdminServiceGetAdminPostListByActivityId_getAdminPostListByActivityId_args');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.I32, 1);
    output.writeI32(this.id);
    output.writeFieldEnd();
  }
  if (this.currentPage !== null && this.currentPage !== undefined) {
    output.writeFieldBegin('currentPage', Thrift.Type.I32, 2);
    output.writeI32(this.currentPage);
    output.writeFieldEnd();
  }
  if (this.pageSize !== null && this.pageSize !== undefined) {
    output.writeFieldBegin('pageSize', Thrift.Type.I32, 3);
    output.writeI32(this.pageSize);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

IActivityAdminServiceGetAdminPostListByActivityId_getAdminPostListByActivityId_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
IActivityAdminServiceGetAdminPostListByActivityId_getAdminPostListByActivityId_result.prototype = {};
IActivityAdminServiceGetAdminPostListByActivityId_getAdminPostListByActivityId_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new TAdminPostQueryData();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

IActivityAdminServiceGetAdminPostListByActivityId_getAdminPostListByActivityId_result.prototype.write = function(output) {
  output.writeStructBegin('IActivityAdminServiceGetAdminPostListByActivityId_getAdminPostListByActivityId_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

IActivityAdminServiceGetAdminPostListByActivityIdClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
IActivityAdminServiceGetAdminPostListByActivityIdClient.prototype = {};
IActivityAdminServiceGetAdminPostListByActivityIdClient.prototype.getAdminPostListByActivityId = function(id, currentPage, pageSize, callback) {
  this.send_getAdminPostListByActivityId(id, currentPage, pageSize, callback); 
  if (!callback) {
    return this.recv_getAdminPostListByActivityId();
  }
};

IActivityAdminServiceGetAdminPostListByActivityIdClient.prototype.send_getAdminPostListByActivityId = function(id, currentPage, pageSize, callback) {
  this.output.writeMessageBegin('getAdminPostListByActivityId', Thrift.MessageType.CALL, this.seqid);
  var args = new IActivityAdminServiceGetAdminPostListByActivityId_getAdminPostListByActivityId_args();
  args.id = id;
  args.currentPage = currentPage;
  args.pageSize = pageSize;
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    var self = this;
    this.output.getTransport().flush(true, function() {
      var result = null;
      try {
        result = self.recv_getAdminPostListByActivityId();
      } catch (e) {
        result = e;
      }
      callback(result);
    });
  } else {
    return this.output.getTransport().flush();
  }
};

IActivityAdminServiceGetAdminPostListByActivityIdClient.prototype.recv_getAdminPostListByActivityId = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new IActivityAdminServiceGetAdminPostListByActivityId_getAdminPostListByActivityId_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'getAdminPostListByActivityId failed: unknown result';
};
