//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

IActivityAdminServiceEditAdminActivity_editAdminActivity_args = function(args) {
  this.activity = null;
  this.activityCommunities = null;
  if (args) {
    if (args.activity !== undefined) {
      this.activity = args.activity;
    }
    if (args.activityCommunities !== undefined) {
      this.activityCommunities = args.activityCommunities;
    }
  }
};
IActivityAdminServiceEditAdminActivity_editAdminActivity_args.prototype = {};
IActivityAdminServiceEditAdminActivity_editAdminActivity_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.activity = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.activityCommunities = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

IActivityAdminServiceEditAdminActivity_editAdminActivity_args.prototype.write = function(output) {
  output.writeStructBegin('IActivityAdminServiceEditAdminActivity_editAdminActivity_args');
  if (this.activity !== null && this.activity !== undefined) {
    output.writeFieldBegin('activity', Thrift.Type.STRING, 1);
    output.writeString(this.activity);
    output.writeFieldEnd();
  }
  if (this.activityCommunities !== null && this.activityCommunities !== undefined) {
    output.writeFieldBegin('activityCommunities', Thrift.Type.STRING, 2);
    output.writeString(this.activityCommunities);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

IActivityAdminServiceEditAdminActivity_editAdminActivity_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
IActivityAdminServiceEditAdminActivity_editAdminActivity_result.prototype = {};
IActivityAdminServiceEditAdminActivity_editAdminActivity_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

IActivityAdminServiceEditAdminActivity_editAdminActivity_result.prototype.write = function(output) {
  output.writeStructBegin('IActivityAdminServiceEditAdminActivity_editAdminActivity_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

IActivityAdminServiceEditAdminActivityClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
IActivityAdminServiceEditAdminActivityClient.prototype = {};
IActivityAdminServiceEditAdminActivityClient.prototype.editAdminActivity = function(activity, activityCommunities, callback) {
  this.send_editAdminActivity(activity, activityCommunities, callback); 
  if (!callback) {
    return this.recv_editAdminActivity();
  }
};

IActivityAdminServiceEditAdminActivityClient.prototype.send_editAdminActivity = function(activity, activityCommunities, callback) {
  this.output.writeMessageBegin('editAdminActivity', Thrift.MessageType.CALL, this.seqid);
  var args = new IActivityAdminServiceEditAdminActivity_editAdminActivity_args();
  args.activity = activity;
  args.activityCommunities = activityCommunities;
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    var self = this;
    this.output.getTransport().flush(true, function() {
      var result = null;
      try {
        result = self.recv_editAdminActivity();
      } catch (e) {
        result = e;
      }
      callback(result);
    });
  } else {
    return this.output.getTransport().flush();
  }
};

IActivityAdminServiceEditAdminActivityClient.prototype.recv_editAdminActivity = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new IActivityAdminServiceEditAdminActivity_editAdminActivity_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'editAdminActivity failed: unknown result';
};
