//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

ISocialAdminServiceUpdateAdminReason_updateAdminReason_args = function(args) {
  this.reason = null;
  if (args) {
    if (args.reason !== undefined) {
      this.reason = args.reason;
    }
  }
};
ISocialAdminServiceUpdateAdminReason_updateAdminReason_args.prototype = {};
ISocialAdminServiceUpdateAdminReason_updateAdminReason_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.reason = new TAdminReason();
        this.reason.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ISocialAdminServiceUpdateAdminReason_updateAdminReason_args.prototype.write = function(output) {
  output.writeStructBegin('ISocialAdminServiceUpdateAdminReason_updateAdminReason_args');
  if (this.reason !== null && this.reason !== undefined) {
    output.writeFieldBegin('reason', Thrift.Type.STRUCT, 1);
    this.reason.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ISocialAdminServiceUpdateAdminReason_updateAdminReason_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ISocialAdminServiceUpdateAdminReason_updateAdminReason_result.prototype = {};
ISocialAdminServiceUpdateAdminReason_updateAdminReason_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ISocialAdminServiceUpdateAdminReason_updateAdminReason_result.prototype.write = function(output) {
  output.writeStructBegin('ISocialAdminServiceUpdateAdminReason_updateAdminReason_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ISocialAdminServiceUpdateAdminReasonClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
ISocialAdminServiceUpdateAdminReasonClient.prototype = {};
ISocialAdminServiceUpdateAdminReasonClient.prototype.updateAdminReason = function(reason, callback) {
  this.send_updateAdminReason(reason, callback); 
  if (!callback) {
    return this.recv_updateAdminReason();
  }
};

ISocialAdminServiceUpdateAdminReasonClient.prototype.send_updateAdminReason = function(reason, callback) {
  this.output.writeMessageBegin('updateAdminReason', Thrift.MessageType.CALL, this.seqid);
  var args = new ISocialAdminServiceUpdateAdminReason_updateAdminReason_args();
  args.reason = reason;
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    var self = this;
    this.output.getTransport().flush(true, function() {
      var result = null;
      try {
        result = self.recv_updateAdminReason();
      } catch (e) {
        result = e;
      }
      callback(result);
    });
  } else {
    return this.output.getTransport().flush();
  }
};

ISocialAdminServiceUpdateAdminReasonClient.prototype.recv_updateAdminReason = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new ISocialAdminServiceUpdateAdminReason_updateAdminReason_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'updateAdminReason failed: unknown result';
};
