//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

ISocialAdminServiceUpdateAdminPostStatus_updateAdminPostStatus_args = function(args) {
  this.post = null;
  if (args) {
    if (args.post !== undefined) {
      this.post = args.post;
    }
  }
};
ISocialAdminServiceUpdateAdminPostStatus_updateAdminPostStatus_args.prototype = {};
ISocialAdminServiceUpdateAdminPostStatus_updateAdminPostStatus_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.post = new TAdminPost();
        this.post.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ISocialAdminServiceUpdateAdminPostStatus_updateAdminPostStatus_args.prototype.write = function(output) {
  output.writeStructBegin('ISocialAdminServiceUpdateAdminPostStatus_updateAdminPostStatus_args');
  if (this.post !== null && this.post !== undefined) {
    output.writeFieldBegin('post', Thrift.Type.STRUCT, 1);
    this.post.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ISocialAdminServiceUpdateAdminPostStatus_updateAdminPostStatus_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ISocialAdminServiceUpdateAdminPostStatus_updateAdminPostStatus_result.prototype = {};
ISocialAdminServiceUpdateAdminPostStatus_updateAdminPostStatus_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ISocialAdminServiceUpdateAdminPostStatus_updateAdminPostStatus_result.prototype.write = function(output) {
  output.writeStructBegin('ISocialAdminServiceUpdateAdminPostStatus_updateAdminPostStatus_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ISocialAdminServiceUpdateAdminPostStatusClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
ISocialAdminServiceUpdateAdminPostStatusClient.prototype = {};
ISocialAdminServiceUpdateAdminPostStatusClient.prototype.updateAdminPostStatus = function(post, callback) {
  this.send_updateAdminPostStatus(post, callback); 
  if (!callback) {
    return this.recv_updateAdminPostStatus();
  }
};

ISocialAdminServiceUpdateAdminPostStatusClient.prototype.send_updateAdminPostStatus = function(post, callback) {
  this.output.writeMessageBegin('updateAdminPostStatus', Thrift.MessageType.CALL, this.seqid);
  var args = new ISocialAdminServiceUpdateAdminPostStatus_updateAdminPostStatus_args();
  args.post = post;
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    var self = this;
    this.output.getTransport().flush(true, function() {
      var result = null;
      try {
        result = self.recv_updateAdminPostStatus();
      } catch (e) {
        result = e;
      }
      callback(result);
    });
  } else {
    return this.output.getTransport().flush();
  }
};

ISocialAdminServiceUpdateAdminPostStatusClient.prototype.recv_updateAdminPostStatus = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new ISocialAdminServiceUpdateAdminPostStatus_updateAdminPostStatus_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'updateAdminPostStatus failed: unknown result';
};
