<?php
namespace ;
/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface IActivityAdminServiceAddAdminActivityIf {
  /**
   * 
   * 新增活动
   * 
   * @param activity
   * @param activityCommunities
   * @return
   * 
   * @author zhijian.li
   * 
   * @param string $activity
   * @param string $activityCommunities
   * @return bool
   */
  public function addAdminActivity($activity, $activityCommunities);
}

class IActivityAdminServiceAddAdminActivityClient implements \IActivityAdminServiceAddAdminActivityIf {
  protected $input_ = null;
  protected $output_ = null;

  protected $seqid_ = 0;

  public function __construct($input, $output=null) {
    $this->input_ = $input;
    $this->output_ = $output ? $output : $input;
  }

  public function addAdminActivity($activity, $activityCommunities)
  {
    $this->send_addAdminActivity($activity, $activityCommunities);
    return $this->recv_addAdminActivity();
  }

  public function send_addAdminActivity($activity, $activityCommunities)
  {
    $args = new \IActivityAdminServiceAddAdminActivity_addAdminActivity_args();
    $args->activity = $activity;
    $args->activityCommunities = $activityCommunities;
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'addAdminActivity', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('addAdminActivity', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_addAdminActivity()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\IActivityAdminServiceAddAdminActivity_addAdminActivity_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \IActivityAdminServiceAddAdminActivity_addAdminActivity_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new \Exception("addAdminActivity failed: unknown result");
  }

}

// HELPER FUNCTIONS AND STRUCTURES

class IActivityAdminServiceAddAdminActivity_addAdminActivity_args {
  static $_TSPEC;

  /**
   * @var string
   */
  public $activity = null;
  /**
   * @var string
   */
  public $activityCommunities = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'activity',
          'type' => TType::STRING,
          ),
        2 => array(
          'var' => 'activityCommunities',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['activity'])) {
        $this->activity = $vals['activity'];
      }
      if (isset($vals['activityCommunities'])) {
        $this->activityCommunities = $vals['activityCommunities'];
      }
    }
  }

  public function getName() {
    return 'IActivityAdminServiceAddAdminActivity_addAdminActivity_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->activity);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->activityCommunities);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('IActivityAdminServiceAddAdminActivity_addAdminActivity_args');
    if ($this->activity !== null) {
      $xfer += $output->writeFieldBegin('activity', TType::STRING, 1);
      $xfer += $output->writeString($this->activity);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->activityCommunities !== null) {
      $xfer += $output->writeFieldBegin('activityCommunities', TType::STRING, 2);
      $xfer += $output->writeString($this->activityCommunities);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class IActivityAdminServiceAddAdminActivity_addAdminActivity_result {
  static $_TSPEC;

  /**
   * @var bool
   */
  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::BOOL,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['success'])) {
        $this->success = $vals['success'];
      }
    }
  }

  public function getName() {
    return 'IActivityAdminServiceAddAdminActivity_addAdminActivity_result';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 0:
          if ($ftype == TType::BOOL) {
            $xfer += $input->readBool($this->success);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('IActivityAdminServiceAddAdminActivity_addAdminActivity_result');
    if ($this->success !== null) {
      $xfer += $output->writeFieldBegin('success', TType::BOOL, 0);
      $xfer += $output->writeBool($this->success);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}


