/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@protocol IKeywordAdminServiceGetKeywordList <NSObject>
- (NSString *) getKeywordList: (NSString *) params;  // throws TException
@end

@interface IKeywordAdminServiceGetKeywordListClient : NSObject <IKeywordAdminServiceGetKeywordList> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface IKeywordAdminServiceGetKeywordListProcessor : NSObject <TProcessor> {
  id <IKeywordAdminServiceGetKeywordList> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithIKeywordAdminServiceGetKeywordList: (id <IKeywordAdminServiceGetKeywordList>) service;
- (id<IKeywordAdminServiceGetKeywordList>) service;
@end

@protocol IKeywordAdminServiceAddKeyword <NSObject>
- (NSString *) addKeyword: (NSString *) params;  // throws TException
@end

@interface IKeywordAdminServiceAddKeywordClient : NSObject <IKeywordAdminServiceAddKeyword> {
id <TProtocol> inProtocol;
id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface IKeywordAdminServiceAddKeywordProcessor : NSObject <TProcessor> {
id <IKeywordAdminServiceAddKeyword> mService;
NSDictionary * mMethodMap;
}
- (id) initWithIKeywordAdminServiceAddKeyword: (id <IKeywordAdminServiceAddKeyword>) service;
- (id<IKeywordAdminServiceAddKeyword>) service;
@end

@protocol IKeywordAdminServiceUpdateKeyword <NSObject>
- (NSString *) updateKeyword: (NSString *) params;  // throws TException
@end

@interface IKeywordAdminServiceUpdateKeywordClient : NSObject <IKeywordAdminServiceUpdateKeyword> {
id <TProtocol> inProtocol;
id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface IKeywordAdminServiceUpdateKeywordProcessor : NSObject <TProcessor> {
id <IKeywordAdminServiceUpdateKeyword> mService;
NSDictionary * mMethodMap;
}
- (id) initWithIKeywordAdminServiceUpdateKeyword: (id <IKeywordAdminServiceUpdateKeyword>) service;
- (id<IKeywordAdminServiceUpdateKeyword>) service;
@end

@protocol IKeywordAdminServiceUpdateKeywordStatus <NSObject>
- (NSString *) updateKeywordStatus: (NSString *) params;  // throws TException
@end

@interface IKeywordAdminServiceUpdateKeywordStatusClient : NSObject <IKeywordAdminServiceUpdateKeywordStatus> {
id <TProtocol> inProtocol;
id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface IKeywordAdminServiceUpdateKeywordStatusProcessor : NSObject <TProcessor> {
id <IKeywordAdminServiceUpdateKeywordStatus> mService;
NSDictionary * mMethodMap;
}
- (id) initWithIKeywordAdminServiceUpdateKeywordStatus: (id <IKeywordAdminServiceUpdateKeywordStatus>) service;
- (id<IKeywordAdminServiceUpdateKeywordStatus>) service;
@end

@protocol IKeywordAdminServiceDeleteKeyword <NSObject>
- (NSString *) deleteKeyword: (NSString *) params;  // throws TException
@end

@interface IKeywordAdminServiceDeleteKeywordClient : NSObject <IKeywordAdminServiceDeleteKeyword> {
id <TProtocol> inProtocol;
id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface IKeywordAdminServiceDeleteKeywordProcessor : NSObject <TProcessor> {
id <IKeywordAdminServiceDeleteKeyword> mService;
NSDictionary * mMethodMap;
}
- (id) initWithIKeywordAdminServiceDeleteKeyword: (id <IKeywordAdminServiceDeleteKeyword>) service;
- (id<IKeywordAdminServiceDeleteKeyword>) service;
@end

@protocol IKeywordAdminServiceDeleteKeywordBatch <NSObject>
- (NSString *) deleteKeywordBatch: (NSString *) params;  // throws TException
@end

@interface IKeywordAdminServiceDeleteKeywordBatchClient : NSObject <IKeywordAdminServiceDeleteKeywordBatch> {
id <TProtocol> inProtocol;
id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface IKeywordAdminServiceDeleteKeywordBatchProcessor : NSObject <TProcessor> {
id <IKeywordAdminServiceDeleteKeywordBatch> mService;
NSDictionary * mMethodMap;
}
- (id) initWithIKeywordAdminServiceDeleteKeywordBatch: (id <IKeywordAdminServiceDeleteKeywordBatch>) service;
- (id<IKeywordAdminServiceDeleteKeywordBatch>) service;
@end

@protocol IKeywordAdminServiceGetKeywordById <NSObject>
- (NSString *) getKeywordById: (NSString *) params;  // throws TException
@end

@interface IKeywordAdminServiceGetKeywordByIdClient : NSObject <IKeywordAdminServiceGetKeywordById> {
id <TProtocol> inProtocol;
id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface IKeywordAdminServiceGetKeywordByIdProcessor : NSObject <TProcessor> {
id <IKeywordAdminServiceGetKeywordById> mService;
NSDictionary * mMethodMap;
}
- (id) initWithIKeywordAdminServiceGetKeywordById: (id <IKeywordAdminServiceGetKeywordById>) service;
- (id<IKeywordAdminServiceGetKeywordById>) service;
@end

@protocol IKeywordAdminServiceImportKeyword <NSObject>
- (NSString *) importKeyword: (NSString *) params;  // throws TException
@end

@interface IKeywordAdminServiceImportKeywordClient : NSObject <IKeywordAdminServiceImportKeyword> {
id <TProtocol> inProtocol;
id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface IKeywordAdminServiceImportKeywordProcessor : NSObject <TProcessor> {
id <IKeywordAdminServiceImportKeyword> mService;
NSDictionary * mMethodMap;
}
- (id) initWithIKeywordAdminServiceImportKeyword: (id <IKeywordAdminServiceImportKeyword>) service;
- (id<IKeywordAdminServiceImportKeyword>) service;
@end

@interface KeywordAdminServiceConstants : NSObject {
}
@end
