/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@interface TAdminCityPost : NSObject <TBase, NSCoding> {
  int32_t __id;
  int32_t __postId;
  int32_t __cityId;
  int32_t __communityId;

  BOOL __id_isset;
  BOOL __postId_isset;
  BOOL __cityId_isset;
  BOOL __communityId_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, getter=postId, setter=setPostId:) int32_t postId;
@property (nonatomic, getter=cityId, setter=setCityId:) int32_t cityId;
@property (nonatomic, getter=communityId, setter=setCommunityId:) int32_t communityId;
#endif

- (id) init;
- (id) initWithId: (int32_t) id postId: (int32_t) postId cityId: (int32_t) cityId communityId: (int32_t) communityId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) id;
- (void) setId: (int32_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (int32_t) postId;
- (void) setPostId: (int32_t) postId;
#endif
- (BOOL) postIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) cityId;
- (void) setCityId: (int32_t) cityId;
#endif
- (BOOL) cityIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) communityId;
- (void) setCommunityId: (int32_t) communityId;
#endif
- (BOOL) communityIdIsSet;

@end

@interface TAdminCityPostConstants : NSObject {
}
@end
