/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


#import "TAdminActivityApply.h"

@implementation TAdminActivityApply

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithId: (int32_t) id postId: (int32_t) postId userId: (int64_t) userId nickName: (NSString *) nickName avatarUrl: (NSString *) avatarUrl postUserId: (int64_t) postUserId createTime: (int64_t) createTime mobile: (NSString *) mobile
{
  self = [super init];
  __id = id;
  __id_isset = YES;
  __postId = postId;
  __postId_isset = YES;
  __userId = userId;
  __userId_isset = YES;
  __nickName = [nickName retain_stub];
  __nickName_isset = YES;
  __avatarUrl = [avatarUrl retain_stub];
  __avatarUrl_isset = YES;
  __postUserId = postUserId;
  __postUserId_isset = YES;
  __createTime = createTime;
  __createTime_isset = YES;
  __mobile = [mobile retain_stub];
  __mobile_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"id"])
  {
    __id = [decoder decodeInt32ForKey: @"id"];
    __id_isset = YES;
  }
  if ([decoder containsValueForKey: @"postId"])
  {
    __postId = [decoder decodeInt32ForKey: @"postId"];
    __postId_isset = YES;
  }
  if ([decoder containsValueForKey: @"userId"])
  {
    __userId = [decoder decodeInt64ForKey: @"userId"];
    __userId_isset = YES;
  }
  if ([decoder containsValueForKey: @"nickName"])
  {
    __nickName = [[decoder decodeObjectForKey: @"nickName"] retain_stub];
    __nickName_isset = YES;
  }
  if ([decoder containsValueForKey: @"avatarUrl"])
  {
    __avatarUrl = [[decoder decodeObjectForKey: @"avatarUrl"] retain_stub];
    __avatarUrl_isset = YES;
  }
  if ([decoder containsValueForKey: @"postUserId"])
  {
    __postUserId = [decoder decodeInt64ForKey: @"postUserId"];
    __postUserId_isset = YES;
  }
  if ([decoder containsValueForKey: @"createTime"])
  {
    __createTime = [decoder decodeInt64ForKey: @"createTime"];
    __createTime_isset = YES;
  }
  if ([decoder containsValueForKey: @"mobile"])
  {
    __mobile = [[decoder decodeObjectForKey: @"mobile"] retain_stub];
    __mobile_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__id_isset)
  {
    [encoder encodeInt32: __id forKey: @"id"];
  }
  if (__postId_isset)
  {
    [encoder encodeInt32: __postId forKey: @"postId"];
  }
  if (__userId_isset)
  {
    [encoder encodeInt64: __userId forKey: @"userId"];
  }
  if (__nickName_isset)
  {
    [encoder encodeObject: __nickName forKey: @"nickName"];
  }
  if (__avatarUrl_isset)
  {
    [encoder encodeObject: __avatarUrl forKey: @"avatarUrl"];
  }
  if (__postUserId_isset)
  {
    [encoder encodeInt64: __postUserId forKey: @"postUserId"];
  }
  if (__createTime_isset)
  {
    [encoder encodeInt64: __createTime forKey: @"createTime"];
  }
  if (__mobile_isset)
  {
    [encoder encodeObject: __mobile forKey: @"mobile"];
  }
}

- (void) dealloc
{
  [__nickName release_stub];
  [__avatarUrl release_stub];
  [__mobile release_stub];
  [super dealloc_stub];
}

- (int32_t) id {
  return __id;
}

- (void) setId: (int32_t) id {
  __id = id;
  __id_isset = YES;
}

- (BOOL) idIsSet {
  return __id_isset;
}

- (void) unsetId {
  __id_isset = NO;
}

- (int32_t) postId {
  return __postId;
}

- (void) setPostId: (int32_t) postId {
  __postId = postId;
  __postId_isset = YES;
}

- (BOOL) postIdIsSet {
  return __postId_isset;
}

- (void) unsetPostId {
  __postId_isset = NO;
}

- (int64_t) userId {
  return __userId;
}

- (void) setUserId: (int64_t) userId {
  __userId = userId;
  __userId_isset = YES;
}

- (BOOL) userIdIsSet {
  return __userId_isset;
}

- (void) unsetUserId {
  __userId_isset = NO;
}

- (NSString *) nickName {
  return [[__nickName retain_stub] autorelease_stub];
}

- (void) setNickName: (NSString *) nickName {
  [nickName retain_stub];
  [__nickName release_stub];
  __nickName = nickName;
  __nickName_isset = YES;
}

- (BOOL) nickNameIsSet {
  return __nickName_isset;
}

- (void) unsetNickName {
  [__nickName release_stub];
  __nickName = nil;
  __nickName_isset = NO;
}

- (NSString *) avatarUrl {
  return [[__avatarUrl retain_stub] autorelease_stub];
}

- (void) setAvatarUrl: (NSString *) avatarUrl {
  [avatarUrl retain_stub];
  [__avatarUrl release_stub];
  __avatarUrl = avatarUrl;
  __avatarUrl_isset = YES;
}

- (BOOL) avatarUrlIsSet {
  return __avatarUrl_isset;
}

- (void) unsetAvatarUrl {
  [__avatarUrl release_stub];
  __avatarUrl = nil;
  __avatarUrl_isset = NO;
}

- (int64_t) postUserId {
  return __postUserId;
}

- (void) setPostUserId: (int64_t) postUserId {
  __postUserId = postUserId;
  __postUserId_isset = YES;
}

- (BOOL) postUserIdIsSet {
  return __postUserId_isset;
}

- (void) unsetPostUserId {
  __postUserId_isset = NO;
}

- (int64_t) createTime {
  return __createTime;
}

- (void) setCreateTime: (int64_t) createTime {
  __createTime = createTime;
  __createTime_isset = YES;
}

- (BOOL) createTimeIsSet {
  return __createTime_isset;
}

- (void) unsetCreateTime {
  __createTime_isset = NO;
}

- (NSString *) mobile {
  return [[__mobile retain_stub] autorelease_stub];
}

- (void) setMobile: (NSString *) mobile {
  [mobile retain_stub];
  [__mobile release_stub];
  __mobile = mobile;
  __mobile_isset = YES;
}

- (BOOL) mobileIsSet {
  return __mobile_isset;
}

- (void) unsetMobile {
  [__mobile release_stub];
  __mobile = nil;
  __mobile_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setPostId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setUserId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setNickName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 5:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setAvatarUrl: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 6:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setPostUserId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 7:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setCreateTime: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 8:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setMobile: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"TAdminActivityApply"];
  if (__id_isset) {
    [outProtocol writeFieldBeginWithName: @"id" type: TType_I32 fieldID: 1];
    [outProtocol writeI32: __id];
    [outProtocol writeFieldEnd];
  }
  if (__postId_isset) {
    [outProtocol writeFieldBeginWithName: @"postId" type: TType_I32 fieldID: 2];
    [outProtocol writeI32: __postId];
    [outProtocol writeFieldEnd];
  }
  if (__userId_isset) {
    [outProtocol writeFieldBeginWithName: @"userId" type: TType_I64 fieldID: 3];
    [outProtocol writeI64: __userId];
    [outProtocol writeFieldEnd];
  }
  if (__nickName_isset) {
    if (__nickName != nil) {
      [outProtocol writeFieldBeginWithName: @"nickName" type: TType_STRING fieldID: 4];
      [outProtocol writeString: __nickName];
      [outProtocol writeFieldEnd];
    }
  }
  if (__avatarUrl_isset) {
    if (__avatarUrl != nil) {
      [outProtocol writeFieldBeginWithName: @"avatarUrl" type: TType_STRING fieldID: 5];
      [outProtocol writeString: __avatarUrl];
      [outProtocol writeFieldEnd];
    }
  }
  if (__postUserId_isset) {
    [outProtocol writeFieldBeginWithName: @"postUserId" type: TType_I64 fieldID: 6];
    [outProtocol writeI64: __postUserId];
    [outProtocol writeFieldEnd];
  }
  if (__createTime_isset) {
    [outProtocol writeFieldBeginWithName: @"createTime" type: TType_I64 fieldID: 7];
    [outProtocol writeI64: __createTime];
    [outProtocol writeFieldEnd];
  }
  if (__mobile_isset) {
    if (__mobile != nil) {
      [outProtocol writeFieldBeginWithName: @"mobile" type: TType_STRING fieldID: 8];
      [outProtocol writeString: __mobile];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"TAdminActivityApply("];
  [ms appendString: @"id:"];
  [ms appendFormat: @"%i", __id];
  [ms appendString: @",postId:"];
  [ms appendFormat: @"%i", __postId];
  [ms appendString: @",userId:"];
  [ms appendFormat: @"%qi", __userId];
  [ms appendString: @",nickName:"];
  [ms appendFormat: @"\"%@\"", __nickName];
  [ms appendString: @",avatarUrl:"];
  [ms appendFormat: @"\"%@\"", __avatarUrl];
  [ms appendString: @",postUserId:"];
  [ms appendFormat: @"%qi", __postUserId];
  [ms appendString: @",createTime:"];
  [ms appendFormat: @"%qi", __createTime];
  [ms appendString: @",mobile:"];
  [ms appendFormat: @"\"%@\"", __mobile];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end


@implementation TAdminActivityApplyConstants
+ (void) initialize {
}
@end

